version: '3.7'
services:
  api-dotnet:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

  database:
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
      
  app:
    restart: always
    build: 
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    tty: true
    links: 
      - database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080